[package]
name = "ver-shim-example-build"
version = "0.1.0"
edition = "2024"

[build-dependencies]
ver-shim-build = { path = "../ver-shim-build" }
ver-shim-example = { path = "../ver-shim-example", artifact = "bin" }
